### ISSUE TITLE
Why do you have multiple Tsung instances up?

### ISSUE THREAD

**Issue by amutz** [scalableinternetservices/GreatReads#42]
Curious, why is it useful to have more than one?  Can't you just reuse the same tsung instance?

Thanks,
Andrew

**Comment by Goom11** [comment]
So we can simultaneously test branches, each implementing their own optimizations.

**Comment by Goom11** [comment]
I just saw the piazza post, I'll remove the extra tsung instances.

**Comment by amutz** [comment]
Thanks.  I know its slightly slower to test them sequentially, but we need to make room for everyone.
